# Generated by Django 4.2.7 on 2023-12-23 17:18
from django.db import migrations, models


def create_default_topics(apps, schema_editor):
    Topic = apps.get_model('BJSTArticle', 'Topic')

    # 定义默认的主题列表
    DEFAULT_TOPICS = ['文化', '国际', '社会']

    # 检查数据库中是否已存在主题
    existing_topics = Topic.objects.filter(text__in=DEFAULT_TOPICS)

    # 如果不存在，则创建默认主题
    for topic_text in DEFAULT_TOPICS:
        if not existing_topics.filter(text=topic_text).exists():
            Topic.objects.create(text=topic_text)


class Migration(migrations.Migration):

    dependencies = [
        ('BJSTArticle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_topics),
    ]
