# Generated by Django 4.2.7 on 2023-12-23 17:33
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    # 通过 loaddata 命令加载 Fixture 文件中的数据
    call_command("loaddata", "static/data/initial_entries.json")


class Migration(migrations.Migration):
    dependencies = [
        ("BJSTArticle", "0001_initial"),
        ("BJSTArticle", "0002_topics")
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
